version: 2
updates:
  - package-ecosystem: github-actions
    schedule:
      interval: quarterly
    reviewers:
      - Scille/ops-code-owners
    assignees:
      - Scille/ops-code-owners
    directory: /
    open-pull-requests-limit: 5
    rebase-strategy: auto
    pull-request-branch-name:
      separator: "-"
    labels:
      - I-Denpendency
      - I-Github-Actions
    groups:
      actions:
        patterns:
          - "*"
