version: 2
updates:
  - package-ecosystem: github-actions
    cooldown:
      default-days: 10
    schedule:
      interval: monthly
    assignees:
      - Scille/ops-code-owners
    directory: /
    open-pull-requests-limit: 5
    rebase-strategy: auto
    pull-request-branch-name:
      separator: "-"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: pre-commit
    directory: /
    cooldown:
      default-days: 10
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    rebase-strategy: auto
    pull-request-branch-name:
      separator: "-"
    groups:
      pre-commit:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    cooldown:
      default-days: 10
    schedule:
      interval: monthly
    open-pull-requests-limit: 15
    rebase-strategy: auto
    pull-request-branch-name:
      separator: "-"
    groups:
      dev-eslint:
        dependency-type: development
        patterns:
          - "@typescript-eslint*"
          - "@vue/eslint*"
          - eslint*
          - vue/eslint*
      dev-prettier:
        dependency-type: development
        patterns:
          - prettier*
      dev-vite:
        dependency-type: development
        patterns:
          - "@vitejs/*"
          - vite*
          - vitest
