version: 2
updates:
  - package-ecosystem: github-actions
    schedule:
      interval: monthly
    assignees:
      - Scille/ops-code-owners
    directory: /
    open-pull-requests-limit: 5
    rebase-strategy: auto
    pull-request-branch-name:
      separator: "-"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    rebase-strategy: auto
    pull-request-branch-name:
      separator: "-"
    groups:
      pre-commit:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    rebase-strategy: auto
    pull-request-branch-name:
      separator: "-"
    groups:
      dev-linter:
        dependency-type: development
        patterns:
          - "@intlify/eslint*"
          - "@typescript-eslint*"
          - "@vue/eslint*"
          - eslint*
          - prettier*
      dev-vite:
        dependency-type: development
        patterns:
          - "@vitejs/*"
          - vite*
          - vitest
      dev-deps:
        dependency-type: development
        patterns:
          - "*"
      prod-deps:
        dependency-type: production
        patterns:
          - "*"
