name: Ci

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}

permissions:
  contents: read

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin v4.2.2
        timeout-minutes: 2

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # pin v4.4.0
        with:
          node-version-file: .tool-versions
          cache: npm
        timeout-minutes: 2

      - name: Install dependencies
        run: npm install --ignore-scripts
        timeout-minutes: 2

      - name: Check lint
        run: npm run lint
        timeout-minutes: 2

      - name: Check prettier
        run: npm run prettier:check
        timeout-minutes: 2

  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin v4.2.2
        timeout-minutes: 2

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # pin v4.4.0
        with:
          node-version-file: .tool-versions
          cache: npm
        timeout-minutes: 2

      - name: Install dependencies
        run: npm install --ignore-scripts
        timeout-minutes: 2

      - name: Run tests
        run: npm run test:unit
        timeout-minutes: 2
