name: Ci

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}

permissions:
  contents: read

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # pin v4.1.3
        timeout-minutes: 2

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # pin v4.0.2
        with:
          node-version-file: .tool-versions
          cache: npm
        timeout-minutes: 2

      - name: Install dependencies
        run: npm install --ignore-scripts
        timeout-minutes: 2

      - name: Check lint
        run: npm run lint
        timeout-minutes: 2

      - name: Check prettier
        run: npm run prettier:check
        timeout-minutes: 2

  test:
    # Currently disable the tests since they are not configured in the repository.
    if: false
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # pin v4.1.3
        timeout-minutes: 2

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # pin v4.0.2
        with:
          node-version-file: .tool-versions
          cache: npm
        timeout-minutes: 2

      - name: Install dependencies
        run: npm install --ignore-scripts
        timeout-minutes: 2

      - name: Run tests
        run: npm run test:unit
        timeout-minutes: 2
